### PR TITLE
Added checking for already set cells and added draw

### PR DESCRIPTION
**Pull request by PucklaJ**
Now there is a loop around the input that breaks when the chosen cell is not already set.
Added draw functionality because the game used to crash when that happens. But some tests need to be rewritten because I changed the return value of check_winner.

### CODE REVIEW

**Comment by timokau** [comment]
Wow, didn't expect to get any contributors here :smile: Could you expand a bit on what you did? I understand the first change, but I'm not sure what you mean with "added draw functionality" (keep in mind that it has been 4 years since I wrote this).

> But some tests need to be rewritten because I changed the return value of check_winner.

So this is not ready yet?

**Comment by PucklaJ** [comment]
I am making this pull request because of hacktoberfest.

> I'm not sure what you mean with "added draw functionality"

Draw means the condition when nobody wins.

> So this is not ready yet?

The game itself is working, but some tests need to be rewritten, because they are using the method is_some(), but, because the return type of check_winner is now GameState instead of Option, is_some() is a method of the Option enum.

**Comment by timokau** [comment]
> I am making this pull request because of hacktoberfest.
> 
> > I'm not sure what you mean with "added draw functionality"
> 
> Draw means the condition when nobody wins.

Ah, I had the other meaning of the word in mind and was confused.

> > So this is not ready yet?
> 
> The game itself is working, but some tests need to be rewritten, because they are using the method is_some(), but, because the return type of check_winner is now GameState instead of Option, is_some() is a method of the Option enum.

And are you planning on doing that?

**Comment by PucklaJ** [comment]
I just fixed the tests. So now it should be ready.

**Comment by timokau** [comment]
Great! Just one more nitpick: Please reframe your commit messages in imperative tone ("Add xyz" instead of "Added xyz") as is [commonly recommended](https://chris.beams.io/posts/git-commit/). You can do that by doing an [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) (`git rebase -i`).

**Comment by PucklaJ** [comment]
I renamed all commits accordingly. But somehow the commits existed two times and so I removed them and force-pushed to the repository.
Thanks for showing me rebase -i. I didn't know it existed.

**Comment by timokau** [comment]
Great, thank you for contributing :)

**Pull request merged**
